version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: spotfinder-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: spotfinder-bot
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    restart: always

volumes:
  pgdata: